CREATE TABLE CUSTOMER_DATA (
    ID INT PRIMARY KEY,
    FIRST_NAME VARCHAR,
    LAST_NAME VARCHAR
);

-- Insert sample data
INSERT INTO CUSTOMER_DATA (ID, FIRST_NAME, LAST_NAME) VALUES (1, 'John', 'Doe');
INSERT INTO CUSTOMER_DATA (ID, FIRST_NAME, LAST_NAME) VALUES (2, 'Jane', 'Smith');
INSERT INTO CUSTOMER_DATA (ID, FIRST_NAME, LAST_NAME) VALUES (3, 'Alice', 'Johnson');
INSERT INTO CUSTOMER_DATA (ID, FIRST_NAME, LAST_NAME) VALUES (4, 'Bob', 'Brown');
